# app-kibana.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co  # Elastic Helm chart repository
    targetRevision: 8.5.1             # Kibana chart version
    chart: kibana                      # Chart name
    helm:
      values: |
          replicas: 1
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          extraEnvs:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging  # Namespace for Kibana (same as Elasticsearch)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true