apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blacklist-umbrella
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/MishaTitov/gitops-blacklist.git
    path: charts/blacklist-umbrella
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: bl-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true