apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.0.0  # Latest kube-prometheus-stack version
    chart: kube-prometheus-stack
    helm:
      values: |
        namespaceOverride: "monitoring"
        admissionWebhooks:
          enabled: false
          patch:
            enabled: false
        prometheusOperator:
          admissionWebhooks:
            enabled: false
            patch:
              enabled: false
          tls:
            enabled: false
        grafana:
          enabled: true
          persistence:
            enabled: true
            type: sts
            storageClassName: "bl-gp2"
            accessModes:
              - ReadWriteOnce
            size: 5Gi
            finalizers:
              - kubernetes.io/pvc-protection
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector:
              matchLabels:
                app.kubernetes.io/instance: kube-prometheus-stack
            resources:
              requests:
                cpu: 500m
                memory: 500Mi
              limits:
                cpu: 1
                memory: 1Gi
        crds:
          enabled: true
        alertmanager:
          enabled: true
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - PruneLast=true