apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-parent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MishaTitov/gitops-blacklist.git
    path: apps
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true