# Use an official Python runtime as the base image
FROM python:3.12.3-slim

# Set the working directory in the container
WORKDIR /utest

# Copy the requirements file into the container
COPY requirements.txt .

# # Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY data /utest/data
COPY routes /utest/routes
COPY app.py /utest/app.py
COPY tests/test_routes.py /utest/test/test_routes.py


# Command to run the tests
CMD ["python", "-m", "unittest", "test/test_routes.py"]