apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bl-tls-secret
  namespace: cert-manager
spec:
  secretName: bl-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: blapp.zapto.org
  dnsNames:
    - blapp.zapto.org