FROM python:3.12.3-slim
WORKDIR /app

COPY data data
COPY routes routes
COPY app.py app.py
COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000

ENTRYPOINT [ "python", "app.py" ]