apiVersion: v1
kind: Service
metadata:
  name: {{ include "blacklist-app.fullname" . }}
  labels:
    {{- include "blacklist-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    {{- include "blacklist-app.selectorLabels" . | nindent 4 }}