apiVersion: v2
name: blacklist-umbrella
description: A Helm umbrella chart for Blacklist
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: blacklist-app
    version: "0.1.0"
    repository: "file://./charts/blacklist-app"  # Local subchart
  - name: mongodb
    version: 16.4.0
    repository: "https://charts.bitnami.com/bitnami"
  - name: ingress-nginx
    version: 4.12.0
    repository: "https://kubernetes.github.io/ingress-nginx"